### ISSUE TITLE
Использование либы https://github.com/v8platform/techlog

### ISSUE THREAD

**Issue by khorevaa** [NuclearAPK/go-techLog1C#1]
Вдохновился твой разработкой, и 

... написал либу для чтения тех журнала.

Исправил чтение многострочных строк в событиях

Посмотри может понравиться.

**Comment by NuclearAPK** [comment]
> Вдохновился твой разработкой, и
> 
> ... написал либу для чтения тех журнала.
> 
> Исправил чтение многострочных строк в событиях
> 
> Посмотри может понравиться.

Привет. В твоей версии получается что будет постоянный мониторинг изменения файлов как я понял? Это крутая задумка. Кстати, я многое доработал на праздниках - и контексты и события с ",". 

По регулярному выражению, которое у тебя используется, не получается заменить на пробелы ,: https://regex101.com/r/6Kvx7y/1

В последней версии я использовал такой подход ('{1}.*?'{1})

**Comment by khorevaa** [comment]
> > Вдохновился твой разработкой, и
> > ... написал либу для чтения тех журнала.
> > Исправил чтение многострочных строк в событиях
> > Посмотри может понравиться.
> 
> Привет. В твоей версии получается что будет постоянный мониторинг изменения файлов как я понял? Это крутая задумка. Кстати, я многое доработал на праздниках - и контексты и события с ",".
> 
> По регулярному выражению, которое у тебя используется, не получается заменить на пробелы ,: https://regex101.com/r/6Kvx7y/1
> 
> В последней версии я использовал такой подход ('{1}.*?'{1})

Ты когда регулярку копировал  не заметил что авто добавились `\`
Вот правильная из либы
https://regex101.com/r/6Kvx7y/2

**Comment by NuclearAPK** [comment]
@khorevaa да, работает этот вариант даже на таких кейсах https://regex101.com/r/kuneNp/1
Спасибо!
